# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/bionic64' # Sử dụng box Ubuntu 18.04 LTS
  config.vm.network "private_network", ip: "192.168.56.99"
  config.vm.hostname = "aspnet"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "aspapp"
    vb.cpus = 4
    vb.memory = "4048" # 2GB bộ nhớ
  end

  config.vm.provision "shell", path: "install.sh"
end

